INSERT INTO paises (nombre, dominio) VALUES
  ("Afganistán","AF"),
  ("Albania","AL"),
  ("Alemania","DE"),
  ("Andorra","AD"),
  ("Angola","AO"),
  ("Anguila","AI"),
  ("Antártida","AQ"),
  ("Antigua y Barbuda","AG"),
  ("Arabia Saudita","SA"),
  ("Argelia","DZ"),
  ("Argentina","AR"),
  ("Armenia","AM"),
  ("Aruba","AW"),
  ("Australia","AU"),
  ("Austria","AT"),
  ("Azerbaiyán","AZ"),
  ("Bélgica","BE"),
  ("Bahamas","BS"),
  ("Bahrein","BH"),
  ("Bangladesh","BD"),
  ("Barbados","BB"),
  ("Belice","BZ"),
  ("Benín","BJ"),
  ("Bhután","BT"),
  ("Bielorrusia","BY"),
  ("Birmania","MM"),
  ("Bolivia","BO"),
  ("Bosnia y Herzegovina","BA"),
  ("Botsuana","BW"),
  ("Brasil","BR"),
  ("Brunéi","BN"),
  ("Bulgaria","BG"),
  ("Burkina Faso","BF"),
  ("Burundi","BI"),
  ("Cabo Verde","CV"),
  ("Camboya","KH"),
  ("Camerún","CM"),
  ("Canadá","CA"),
  ("Chad","TD"),
  ("Chile","CL"),
  ("China","CN"),
  ("Chipre","CY"),
  ("Ciudad del Vaticano","VA"),
  ("Colombia","CO"),
  ("Comoras","KM"),
  ("República del Congo","CG"),
  ("República Democrática del Congo","CD"),
  ("Corea del Norte","KP"),
  ("Corea del Sur","KR"),
  ("Costa de Marfil","CI"),
  ("Costa Rica","CR"),
  ("Croacia","HR"),
  ("Cuba","CU"),
  ("Curazao","CW"),
  ("Dinamarca","DK"),
  ("Dominica","DM"),
  ("Ecuador","EC"),
  ("Egipto","EG"),
  ("El Salvador","SV"),
  ("Emiratos Árabes Unidos","AE"),
  ("Eritrea","ER"),
  ("Eslovaquia","SK"),
  ("Eslovenia","SI"),
  ("España","ES"),
  ("Estados Unidos de América","US"),
  ("Estonia","EE"),
  ("Etiopía","ET"),
  ("Filipinas","PH"),
  ("Finlandia","FI"),
  ("Fiyi","FJ"),
  ("Francia","FR"),
  ("Gabón","GA"),
  ("Gambia","GM"),
  ("Georgia","GE"),
  ("Ghana","GH"),
  ("Gibraltar","GI"),
  ("Granada","GD"),
  ("Grecia","GR"),
  ("Groenlandia","GL"),
  ("Guadalupe","GP"),
  ("Guam","GU"),
  ("Guatemala","GT"),
  ("Guayana Francesa","GF"),
  ("Guernsey","GG"),
  ("Guinea","GN"),
  ("Guinea Ecuatorial","GQ"),
  ("Guinea-Bissau","GW"),
  ("Guyana","GY"),
  ("Haití","HT"),
  ("Honduras","HN"),
  ("Hong kong","HK"),
  ("Hungría","HU"),
  ("India","IN"),
  ("Indonesia","ID"),
  ("Irán","IR"),
  ("Irak","IQ"),
  ("Irlanda","IE"),
  ("Isla Bouvet","BV"),
  ("Isla de Man","IM"),
  ("Isla de Navidad","CX"),
  ("Isla Norfolk","NF"),
  ("Islandia","IS"),
  ("Islas Bermudas","BM"),
  ("Islas Caimán","KY"),
  ("Islas Cocos (Keeling)","CC"),
  ("Islas Cook","CK"),
  ("Islas de Åland","AX"),
  ("Islas Feroe","FO"),
  ("Islas Georgias del Sur y Sandwich del Sur","GS"),
  ("Islas Heard y McDonald","HM"),
  ("Islas Maldivas","MV"),
  ("Islas Malvinas","FK"),
  ("Islas Marianas del Norte","MP"),
  ("Islas Marshall","MH"),
  ("Islas Pitcairn","PN"),
  ("Islas Salomón","SB"),
  ("Islas Turcas y Caicos","TC"),
  ("Islas Ultramarinas Menores de Estados Unidos","UM"),
  ("Islas Vírgenes Británicas","VG"),
  ("Islas Vírgenes de los Estados Unidos","VI"),
  ("Israel","IL"),
  ("Italia","IT"),
  ("Jamaica","JM"),
  ("Japón","JP"),
  ("Jersey","JE"),
  ("Jordania","JO"),
  ("Kazajistán","KZ"),
  ("Kenia","KE"),
  ("Kirguistán","KG"),
  ("Kiribati","KI"),
  ("Kuwait","KW"),
  ("Líbano","LB"),
  ("Laos","LA"),
  ("Lesoto","LS"),
  ("Letonia","LV"),
  ("Liberia","LR"),
  ("Libia","LY"),
  ("Liechtenstein","LI"),
  ("Lituania","LT"),
  ("Luxemburgo","LU"),
  ("México","MX"),
  ("Mónaco","MC"),
  ("Macao","MO"),
  ("Macedônia","MK"),
  ("Madagascar","MG"),
  ("Malasia","MY"),
  ("Malawi","MW"),
  ("Mali","ML"),
  ("Malta","MT"),
  ("Marruecos","MA"),
  ("Martinica","MQ"),
  ("Mauricio","MU"),
  ("Mauritania","MR"),
  ("Mayotte","YT"),
  ("Micronesia","FM"),
  ("Moldavia","MD"),
  ("Mongolia","MN"),
  ("Montenegro","ME"),
  ("Montserrat","MS"),
  ("Mozambique","MZ"),
  ("Namibia","NA"),
  ("Nauru","NR"),
  ("Nepal","NP"),
  ("Nicaragua","NI"),
  ("Niger","NE"),
  ("Nigeria","NG"),
  ("Niue","NU"),
  ("Noruega","NO"),
  ("Nueva Caledonia","NC"),
  ("Nueva Zelanda","NZ"),
  ("Omán","OM"),
  ("Países Bajos","NL"),
  ("Pakistán","PK"),
  ("Palau","PW"),
  ("Palestina","PS"),
  ("Panamá","PA"),
  ("Papúa Nueva Guinea","PG"),
  ("Paraguay","PY"),
  ("Perú","PE"),
  ("Polinesia Francesa","PF"),
  ("Polonia","PL"),
  ("Portugal","PT"),
  ("Puerto Rico","PR"),
  ("Qatar","QA"),
  ("Reino Unido","GB"),
  ("República Centroafricana","CF"),
  ("República Checa","CZ"),
  ("República Dominicana","DO"),
  ("República de Sudán del Sur","SS"),
  ("Reunión","RE"),
  ("Ruanda","RW"),
  ("Rumanía","RO"),
  ("Rusia","RU"),
  ("Sahara Occidental","EH"),
  ("Samoa","WS"),
  ("Samoa Americana","AS"),
  ("San Bartolomé","BL"),
  ("San Cristóbal y Nieves","KN"),
  ("San Marino","SM"),
  ("San Martín (Francia)","MF"),
  ("San Pedro y Miquelón","PM"),
  ("San Vicente y las Granadinas","VC"),
  ("Santa Elena","SH"),
  ("Santa Lucía","LC"),
  ("Santo Tomé y Príncipe","ST"),
  ("Senegal","SN"),
  ("Serbia","RS"),
  ("Seychelles","SC"),
  ("Sierra Leona","SL"),
  ("Singapur","SG"),
  ("Sint Maarten","SX"),
  ("Siria","SY"),
  ("Somalia","SO"),
  ("Sri lanka","LK"),
  ("Sudáfrica","ZA"),
  ("Sudán","SD"),
  ("Suecia","SE"),
  ("Suiza","CH"),
  ("Surinám","SR"),
  ("Svalbard y Jan Mayen","SJ"),
  ("Swazilandia","SZ"),
  ("Tayikistán","TJ"),
  ("Tailandia","TH"),
  ("Taiwán","TW"),
  ("Tanzania","TZ"),
  ("Territorio Británico del Océano Índico","IO"),
  ("Territorios Australes y Antárticas Franceses","TF"),
  ("Timor Oriental","TL"),
  ("Togo","TG"),
  ("Tokelau","TK"),
  ("Tonga","TO"),
  ("Trinidad y Tobago","TT"),
  ("Tunez","TN"),
  ("Turkmenistán","TM"),
  ("Turquía","TR"),
  ("Tuvalu","TV"),
  ("Ucrania","UA"),
  ("Uganda","UG"),
  ("Uruguay","UY"),
  ("Uzbekistán","UZ"),
  ("Vanuatu","VU"),
  ("Venezuela","VE"),
  ("Vietnam","VN"),
  ("Wallis y Futuna","WF"),
  ("Yemen","YE"),
  ("Yibuti","DJ"),
  ("Zambia","ZM"),
  ("Zimbabue","ZW");

  INSERT INTO artistas (nombre, foto, edad, pais) VALUES
  ("Chester Bennington", "https://cdn.discordapp.com/attachments/1011284720350412802/1045372822844874813/Linkin_Park-Rock_im_Park_2014-_by_2eight_3SC0327.jpg", "1976-03-20", 66)
  ("Maria Becerra", "https://cdn.discordapp.com/attachments/1011284720350412802/1045374817009934396/97c4812b09c0a8223dfc2b8d056f2e2b.jpg", "2000-02-12", 12 )
  ("Billie Eilish","https://cdn.discordapp.com/attachments/1011284720350412802/1045375230392160306/BillieEilishO2160622_19_of_45_52153214339_cropped_3.jpg","2001-12-18", 66)
  ("Kygo", "https://cdn.discordapp.com/attachments/1011284720350412802/1045375231142920302/Kygo_28481718120_2_cropped.jpg","1991-09-11", 211)
  ("Adam Levine","https://cdn.discordapp.com/attachments/1011284720350412802/1045375230891278397/640px-AdamLevine2011.jpg", "1979-03-18", 66)
  ("Feid", "https://cdn.discordapp.com/attachments/1011284720350412802/1045375230698324038/channels4_profile.jpg", "1992-08-19", 45)

  INSERT INTO album (nombre, lanzamiento, numerocanciones, duracion) VALUES
  ("Hybrid Theory", "2000-10-24", "12", "38:50:00")
  ("Animal", "2021-08-26", "11", "24:27:00")
  ("Cloud Nine", "2016-05-13", "15", "55:49:00")
  ("13 reasons why", " 2018-05-18", "20", "76:00:00")
  ("Songs about jane", "2002-06-25", "45:57:00")
  ( "Feliz cumpleaños", "2022-09-14", "15", "53:04:00")
  
  INSERT INTO canciones (album_id, nombre, genero, lanzamiento) VALUES
  (1,"In the end", "Rock alternativo", "2009-10-29")
  (2,"Episodios", "Urbano latino", "2022-02-16")
  (3,"Lovely", "Pop", "2018-05-29")
  (4,"Firestone", "Electronica", "2016-03-10")
  (5,"She will be loved", "Pop rock", " 2003-06-22")
  (6, "Ferxxo 100", "Reggaeton", "2022-06-03")

  INSERT INTO genero (cancion_id, descripcion) VALUES
  (1,"El rock alternativo es un subgénero del rock que tiene sus orígenes e influencias musicales en estilos musicales tan variados como el punk rock, el post-punk, el new wave, el hardcore, el pop rock y la música folk.")
  (2, "La expresión música urbana puede referirse a: Un conjunto de estilos musicales latinos populares desde los años 2000 como el reguetón, el trap latino y el hip hop latino. El término urban, para referirse a estilos musicales afroamericanos de los años 2000.")
  (3, "La música electrónica es aquella hecha utilizando tecnologías de audio analógica y/o digital, donde este elemento es una clave estética de la obra.")
  (4, "Un cierto tipo de música ligera y popular derivado de estilos musicales negros y de la música folclórica británica")
  (5, "Un subgénero de la música pop que utiliza pegadizas canciones pop que son sobre todo basadas en la guitarra. Starostin afirma que la mayor parte de lo que tradicionalmente se llama power pop cae en el subgénero pop rock.")
  (6, "El reggaetón o reguetón es un género de música que combina el reggae con el rap y el hip hop. Surgió en América Central a finales de la década de 1980, pero tardó unos veinte años en popularizarse y llegar a otras regiones del mundo.")

