CREATE DATABASE IF NOT EXISTS Música;

USE Música;

CREATE TABLE paises(
  pais_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  dominio CHAR(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE artistas(
  artista_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  descripcion TEXT,
  foto VARCHAR(255),
  edad INTEGER UNSIGNED,
  id_pais INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY (id_pais)
    REFERENCES paises(pais_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE albumes(
  album_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  artista_id INTEGER UNSIGNED,
  nombre VARCHAR(50) NOT NULL,
  fecha DATETIME NOT NULL,
  numero INTEGER UNSIGNED,
  duracion FLOAT NOT NULL,
  FOREIGN KEY(artista_id)
    REFERENCES Artistas(artista_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE canciones(
  cancion_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  genero VARCHAR(50) NOT NULL,
  fecha DATETIME NOT NULL,
  id_album INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY (id_album)
    REFERENCES albumes(album_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE generos(
genero_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  descripcion TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;